import { App, Notice } from 'obsidian';

export const DEFAULT_IGNORE_CONTENT = `
# --- Generated by Syncthing Controller ---
# Ignora configurações de janela/workspace (Evita conflitos de layout entre PC/Mobile)
.obsidian/workspace*

# Ignora cache de instalador
.obsidian/installer.json

# Ignora pastas ocultas do sistema (opcional)
# .*
`;

export class IgnoreManager {
    app: App;
    ignoreFile = '.stignore';

    constructor(app: App) {
        this.app = app;
    }

    async ensureDefaults() {
        const exists = await this.app.vault.adapter.exists(this.ignoreFile);
        
        if (!exists) {
            try {
                await this.app.vault.adapter.write(this.ignoreFile, DEFAULT_IGNORE_CONTENT.trim());
                console.log('Syncthing Controller: .stignore criado com sucesso.');
            } catch (e) {
                console.error('Erro ao criar .stignore:', e);
            }
        }
    }

    async readIgnoreFile(): Promise<string> {
        if (await this.app.vault.adapter.exists(this.ignoreFile)) {
            return await this.app.vault.adapter.read(this.ignoreFile);
        }
        return ''; 
    }

    async saveIgnoreFile(content: string) {
        await this.app.vault.adapter.write(this.ignoreFile, content);
    }
}